appname: "Dancebin"
layout: "main"
charset: "UTF-8"

logger: "console"
log: "debug"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'


plugins:
  DBIC:
    default:
      schema_class: 'Dancebin::Schema'
      dsn: dbi:SQLite:dbname=data/dancebin.db
      options:
        sqlite_unicode: 1

# Comment out for production
show_errors: 1

# Sets the expiration for posts
# Options can be any combination of weeks, days, hours, minutes, seconds
expiration:
    weeks: 1
